theme: jekyll-theme-chirpy


social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: AbelChe
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/abelche      # change to your twitter homepage

theme_mode: dark
